"""Hand-built IFC files for the import tests.

A small house the way another program might write it: layer sets with usage on the walls (the
first layer on a side the file says), openings that void their wall, floor slabs with their finish
layers, spaces under their storey. Every number is chosen so the expected result can be worked out
by hand; the geometry is written explicitly (extruded rectangles), nothing is generated by UEA.
"""
# pyright: reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnknownArgumentType=false, reportMissingTypeStubs=false, reportAttributeAccessIssue=false

import math
import uuid
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Literal

import ifcopenshell
import ifcopenshell.api.aggregate
import ifcopenshell.api.context
import ifcopenshell.api.feature
import ifcopenshell.api.material
import ifcopenshell.api.pset
import ifcopenshell.api.root
import ifcopenshell.api.spatial
import ifcopenshell.api.type
import ifcopenshell.guid

Vec = tuple[float, float]
NS = uuid.UUID("5d3c9d0c-6a0b-4f5e-9a61-0c3f5c2f7a10")

OUTER = (("Aussenputz", 0.02), ("Mauerwerk", 0.30), ("Innenputz", 0.015))
"""Outside to inside: total 0.335 m, the core 0.30 m with 0.02 m outside and 0.015 m inside."""
INNER = (("Gipsputz", 0.01), ("Kalksandstein", 0.115), ("Gipsputz", 0.01))
FLOOR = (("Fliese", 0.02), ("Estrich", 0.13), ("Stahlbeton", 0.20))
"""A floor slab, top to bottom: finish 0.15 m on a 0.20 m core."""


@dataclass
class WallSpec:
    name: str
    p0: Vec
    p1: Vec
    """The ends of the line through the centre of the core."""
    storey: str = "EG"
    layers: tuple[tuple[str, float], ...] = OUTER
    first: Vec | None = None
    """World direction from the core centre to the first layer; none: no layer set usage, and the
    body is centred on the line."""
    z0: float = -0.15
    z1: float = 2.55
    type_name: str | None = None
    lb: bool = False
    status: str | None = None
    reverse: bool = False
    """The wall's own x axis runs from p1 to p0."""
    body: float | None = None
    """Thickness of the body where it differs from the layers' total (centred on the line)."""


@dataclass
class OpeningSpec:
    name: str
    wall: str
    s0: float
    """Along the wall from p0 (not from the start of the body)."""
    width: float
    sill: float
    """From the FFL of the storey."""
    height: float
    kind: str = "win"
    type_name: str | None = None
    u: float | None = None


@dataclass
class SlabSpec:
    name: str
    storey: str
    z1: float
    """Top of the finish."""
    outline: tuple[Vec, ...]
    layers: tuple[tuple[str, float], ...] = FLOOR
    sense: str = "NEGATIVE"
    """Direction sense of the layer set usage: POSITIVE puts the first layer at the bottom."""
    type_name: str | None = "Decke 35"


@dataclass
class SpaceSpec:
    name: str
    storey: str
    outline: tuple[Vec, ...]
    long_name: str | None = None
    z0: float = 0.0
    height: float = 2.5
    parent: bool = True
    """Aggregated under its storey, as most programs do; otherwise it hangs in the air and only its
    height says where it is."""


@dataclass
class House:
    storeys: dict[str, float] = field(default_factory=lambda: {"EG": 0.0, "OG": 2.9})
    walls: list[WallSpec] = field(default_factory=list[WallSpec])
    openings: list[OpeningSpec] = field(default_factory=list[OpeningSpec])
    slabs: list[SlabSpec] = field(default_factory=list[SlabSpec])
    spaces: list[SpaceSpec] = field(default_factory=list[SpaceSpec])
    extras: list[str] = field(default_factory=list[str])
    """Classes of things UEA does not map (IfcRoof, IfcColumn, ...), one product each."""
    app: str = "Test-CAD 1.0"
    schema: Literal["IFC2X3", "IFC4", "IFC4X3"] = "IFC4"

    def wall(self, name: str) -> WallSpec:
        return next(w for w in self.walls if w.name == name)

    def without(self, *names: str) -> "House":
        """A copy without these elements (a wall takes its openings with it)."""
        gone = set(names)
        return replace(
            self,
            walls=[w for w in self.walls if w.name not in gone],
            openings=[o for o in self.openings if o.name not in gone and o.wall not in gone],
            slabs=[x for x in self.slabs if x.name not in gone],
            spaces=[x for x in self.spaces if x.name not in gone],
        )

    def raised(self, dz: float) -> "House":
        """The same house with every height in the file `dz` higher."""
        return replace(
            self,
            storeys={k: v + dz for k, v in self.storeys.items()},
            walls=[replace(w, z0=w.z0 + dz, z1=w.z1 + dz) for w in self.walls],
            slabs=[replace(x, z1=x.z1 + dz) for x in self.slabs],
            spaces=[replace(x, z0=x.z0 + dz) for x in self.spaces],
        )


def unit(a: Vec, b: Vec) -> Vec:
    d = math.hypot(b[0] - a[0], b[1] - a[1])
    return ((b[0] - a[0]) / d, (b[1] - a[1]) / d)


def house() -> House:
    """Two storeys, an outline of 6 m by 4 m around the core centre lines.

    EG: four outer walls (first layer outside), one inner wall at x=3.5 with a door, two windows,
    a floor slab, an open-plan east part in two spaces. OG: the outer walls under no slab, one
    window, a floor slab and one space.
    """
    h = House()
    out = {
        "south": ((0.0, 0.0), (6.0, 0.0), (0.0, -1.0)),
        "east": ((6.0, 0.0), (6.0, 4.0), (1.0, 0.0)),
        "north": ((6.0, 4.0), (0.0, 4.0), (0.0, 1.0)),
        "west": ((0.0, 4.0), (0.0, 0.0), (-1.0, 0.0)),
    }
    for storey, z0, z1 in (("EG", -0.15, 2.55), ("OG", 2.75, 5.4)):
        for side, (p0, p1, first) in out.items():
            h.walls.append(
                WallSpec(f"{storey}-{side}", p0, p1, storey, OUTER, first, z0, z1, "AW 33.5", True)
            )
    h.walls.append(
        WallSpec(
            "EG-inner", (3.5, 0.165), (3.5, 3.835), "EG", INNER, (-1.0, 0.0), -0.15, 2.55, "IW 11.5"
        )
    )
    h.openings += [
        OpeningSpec("EG-win-1", "EG-south", 1.0, 1.2, 0.9, 1.35, "win", "Fenster 120", 1.1),
        OpeningSpec("EG-win-2", "EG-north", 1.0, 0.6, 1.2, 0.7, "win", "Fenster 60", 1.1),
        OpeningSpec("EG-door", "EG-inner", 0.8, 0.9, 0.0, 2.01, "door", "Tuer 90", None),
        OpeningSpec("OG-win-1", "OG-south", 2.0, 1.2, 0.9, 1.35, "win", "Fenster 120", 1.1),
    ]
    ring = ((-0.2, -0.2), (6.2, -0.2), (6.2, 4.2), (-0.2, 4.2))
    h.slabs += [
        SlabSpec("EG-slab", "EG", 0.0, ring),
        SlabSpec("OG-slab", "OG", 2.9, ring, sense="POSITIVE"),
    ]
    h.spaces += [
        SpaceSpec(
            "R1",
            "EG",
            ((0.165, 0.165), (3.4325, 0.165), (3.4325, 3.835), (0.165, 3.835)),
            "Wohnzimmer",
        ),
        SpaceSpec(
            "R2", "EG", ((3.5675, 0.165), (5.835, 0.165), (5.835, 2.0), (3.5675, 2.0)), "Küche"
        ),
        SpaceSpec(
            "R3", "EG", ((3.5675, 2.0), (5.835, 2.0), (5.835, 3.835), (3.5675, 3.835)), "Essen"
        ),
        SpaceSpec(
            "R4",
            "OG",
            ((0.165, 0.165), (5.835, 0.165), (5.835, 3.835), (0.165, 3.835)),
            "Schlafen",
            z0=2.9,
            parent=False,
        ),
    ]
    h.extras = ["IfcRoof", "IfcColumn"]
    return h


# ---------- writing ----------


class Writer:
    def __init__(self, h: House) -> None:
        self.h = h
        self.f = ifcopenshell.file(schema=h.schema)
        self.guids: dict[str, str] = {}
        self.materials: dict[str, Any] = {}
        self.types: dict[str, Any] = {}

    def guid(self, key: str) -> str:
        return ifcopenshell.guid.compress(uuid.uuid5(NS, key).hex)

    def entity(
        self, cls: str, key: str, name: str | None = None, predefined: str | None = None
    ) -> Any:
        e = ifcopenshell.api.root.create_entity(
            self.f, ifc_class=cls, predefined_type=predefined, name=name
        )
        e.GlobalId = self.guid(key)
        if name is not None and cls not in ("IfcProject", "IfcSite", "IfcBuilding"):
            self.guids[name] = e.GlobalId
        return e

    def pt(self, *c: float) -> Any:
        return self.f.createIfcCartesianPoint([float(x) for x in c])

    def axis(self, origin: tuple[float, ...], x: Vec | None = None) -> Any:
        ref = self.f.createIfcDirection([float(x[0]), float(x[1]), 0.0]) if x else None
        return self.f.createIfcAxis2Placement3D(self.pt(*origin), None, ref)

    def placed(self, parent: Any, origin: tuple[float, ...], x: Vec | None = None) -> Any:
        return self.f.createIfcLocalPlacement(parent, self.axis(origin, x))

    def body(self, solid: Any) -> Any:
        rep = self.f.createIfcShapeRepresentation(self.ctx, "Body", "SweptSolid", [solid])
        return self.f.createIfcProductDefinitionShape(None, None, [rep])

    def prism(self, outline: tuple[Vec, ...], z0: float, height: float) -> Any:
        pts = [self.f.createIfcCartesianPoint([float(x), float(y)]) for x, y in outline]
        ring = self.f.createIfcPolyline([*pts, pts[0]])
        profile = self.f.createIfcArbitraryClosedProfileDef("AREA", None, ring)
        return self.f.createIfcExtrudedAreaSolid(
            profile,
            self.axis((0.0, 0.0, z0)),
            self.f.createIfcDirection([0.0, 0.0, 1.0]),
            float(height),
        )

    def material(self, name: str) -> Any:
        if name not in self.materials:
            self.materials[name] = ifcopenshell.api.material.add_material(self.f, name=name)
        return self.materials[name]

    def layer_set(self, name: str, layers: tuple[tuple[str, float], ...]) -> Any:
        ls = ifcopenshell.api.material.add_material_set(
            self.f, name=name, set_type="IfcMaterialLayerSet"
        )
        for material, t in layers:
            layer = ifcopenshell.api.material.add_layer(
                self.f, layer_set=ls, material=self.material(material)
            )
            ifcopenshell.api.material.edit_layer(
                self.f, layer=layer, attributes={"LayerThickness": float(t), "Name": material}
            )
        return ls

    def usage(self, product: Any, ls: Any, direction: str, sense: str, offset: float) -> None:
        use = self.f.createIfcMaterialLayerSetUsage(ls, direction, sense, float(offset))
        self.f.createIfcRelAssociatesMaterial(
            self.guid(f"mat/{product.GlobalId}"), None, None, None, [product], use
        )

    def type_of(self, cls: str, name: str) -> Any:
        if name not in self.types:
            self.types[name] = self.entity(cls, f"type/{name}", name)
        return self.types[name]

    def pset(self, product: Any, name: str, props: dict[str, Any]) -> None:
        ps = ifcopenshell.api.pset.add_pset(self.f, product=product, name=name)
        ifcopenshell.api.pset.edit_pset(self.f, pset=ps, properties=props)

    # --- the file

    def write(self, path: Path) -> dict[str, str]:
        f, h = self.f, self.h
        project = self.entity("IfcProject", "project", "Testhaus")
        project.UnitsInContext = f.createIfcUnitAssignment(
            [f.createIfcSIUnit(None, "LENGTHUNIT", None, "METRE")]
        )
        model_ctx = ifcopenshell.api.context.add_context(f, context_type="Model")
        self.ctx = ifcopenshell.api.context.add_context(
            f,
            context_type="Model",
            context_identifier="Body",
            target_view="MODEL_VIEW",
            parent=model_ctx,
        )
        site = self.entity("IfcSite", "site", "Site")
        building = self.entity("IfcBuilding", "building", "Haus")
        ifcopenshell.api.aggregate.assign_object(f, products=[site], relating_object=project)
        ifcopenshell.api.aggregate.assign_object(f, products=[building], relating_object=site)
        site.ObjectPlacement = self.placed(None, (0.0, 0.0, 0.0))
        building.ObjectPlacement = self.placed(site.ObjectPlacement, (0.0, 0.0, 0.0))
        self.storeys: dict[str, Any] = {}
        for name, z in h.storeys.items():
            st = self.entity("IfcBuildingStorey", f"storey/{name}", name)
            st.Elevation = float(z)
            st.ObjectPlacement = self.placed(building.ObjectPlacement, (0.0, 0.0, z))
            self.storeys[name] = st
        ifcopenshell.api.aggregate.assign_object(
            f, products=list(self.storeys.values()), relating_object=building
        )
        self.contained: dict[str, list[Any]] = {k: [] for k in self.storeys}
        walls: dict[str, Any] = {}
        for w in h.walls:
            walls[w.name] = self.wall(w)
        for o in h.openings:
            self.opening(o, h.wall(o.wall), walls[o.wall])
        for s in h.slabs:
            self.slab(s)
        for sp in h.spaces:
            self.space(sp)
        for cls in h.extras:
            e = self.entity(cls, f"extra/{cls}", cls)
            e.ObjectPlacement = self.placed(self.storeys["EG"].ObjectPlacement, (0.0, 0.0, 0.0))
            self.contained["EG"].append(e)
        for name, items in self.contained.items():
            if items:
                ifcopenshell.api.spatial.assign_container(
                    f, products=items, relating_structure=self.storeys[name]
                )
        f.header.file_name.originating_system = h.app
        f.write(str(path))
        return self.guids

    def wall(self, w: WallSpec) -> Any:
        e = self.entity(
            "IfcWall", f"wall/{w.name}", w.name, "SOLIDWALL" if w.lb else "PARTITIONING"
        )
        st_z = self.h.storeys[w.storey]
        a, b = (w.p1, w.p0) if w.reverse else (w.p0, w.p1)
        u = unit(a, b)
        left = (-u[1], u[0])
        length = math.hypot(b[0] - a[0], b[1] - a[1])
        total = sum(t for _, t in w.layers)
        core = max(range(len(w.layers)), key=lambda i: w.layers[i][1])
        if w.first is None:
            width = w.body or total
            lo, hi = -width / 2, width / 2
            ls = self.layer_set(w.type_name or w.name, w.layers)
            ifcopenshell.api.material.assign_material(
                self.f, products=[e], type="IfcMaterialLayerSet", material=ls
            )
        else:
            before = sum(t for _, t in w.layers[:core]) + w.layers[core][1] / 2
            towards_left = w.first[0] * left[0] + w.first[1] * left[1] > 0
            if towards_left:
                lo, hi = before - total, before
                sense, offset = "NEGATIVE", before
            else:
                lo, hi = -before, total - before
                sense, offset = "POSITIVE", -before
            ls = self.layer_set(w.type_name or w.name, w.layers)
            self.usage(e, ls, "AXIS2", sense, offset)
        e.ObjectPlacement = self.placed(
            self.storeys[w.storey].ObjectPlacement, (a[0], a[1], w.z0 - st_z), u
        )
        outline = ((0.0, lo), (length, lo), (length, hi), (0.0, hi))
        e.Representation = self.body(self.prism(outline, 0.0, w.z1 - w.z0))
        if w.type_name:
            ifcopenshell.api.type.assign_type(
                self.f,
                related_objects=[e],
                relating_type=self.type_of("IfcWallType", w.type_name),
                should_map_representations=False,
            )
        props: dict[str, Any] = {"LoadBearing": w.lb}
        if w.status:
            props["Status"] = w.status
        self.pset(e, "Pset_WallCommon", props)
        self.contained[w.storey].append(e)
        return e

    def opening(self, o: OpeningSpec, w: WallSpec, wall: Any) -> None:
        a = w.p0
        u = unit(w.p0, w.p1)
        left = (-u[1], u[0])
        box = (
            (a[0] + u[0] * o.s0 - left[0] * 0.25, a[1] + u[1] * o.s0 - left[1] * 0.25),
            (
                a[0] + u[0] * (o.s0 + o.width) - left[0] * 0.25,
                a[1] + u[1] * (o.s0 + o.width) - left[1] * 0.25,
            ),
            (
                a[0] + u[0] * (o.s0 + o.width) + left[0] * 0.25,
                a[1] + u[1] * (o.s0 + o.width) + left[1] * 0.25,
            ),
            (a[0] + u[0] * o.s0 + left[0] * 0.25, a[1] + u[1] * o.s0 + left[1] * 0.25),
        )
        st = self.storeys[w.storey]
        op = self.entity("IfcOpeningElement", f"opening/{o.name}", None, "OPENING")
        op.ObjectPlacement = self.placed(st.ObjectPlacement, (0.0, 0.0, 0.0))
        op.Representation = self.body(self.prism(box, o.sill, o.height))
        ifcopenshell.api.feature.add_feature(self.f, feature=op, element=wall)
        cls = "IfcDoor" if o.kind == "door" else "IfcWindow"
        e = self.entity(cls, f"{o.kind}/{o.name}", o.name, "DOOR" if o.kind == "door" else "WINDOW")
        e.ObjectPlacement = self.placed(st.ObjectPlacement, (0.0, 0.0, 0.0))
        e.OverallWidth = float(o.width)
        e.OverallHeight = float(o.height)
        e.Representation = self.body(self.prism(box, o.sill, o.height))
        ifcopenshell.api.feature.add_filling(self.f, opening=op, element=e)
        if o.type_name:
            t = self.type_of("IfcDoorType" if o.kind == "door" else "IfcWindowType", o.type_name)
            ifcopenshell.api.type.assign_type(
                self.f, related_objects=[e], relating_type=t, should_map_representations=False
            )
        if o.u is not None:
            self.pset(
                e,
                "Pset_DoorCommon" if o.kind == "door" else "Pset_WindowCommon",
                {"ThermalTransmittance": o.u},
            )
        self.contained[w.storey].append(e)

    def slab(self, s: SlabSpec) -> None:
        e = self.entity("IfcSlab", f"slab/{s.name}", s.name, "FLOOR")
        total = sum(t for _, t in s.layers)
        e.ObjectPlacement = self.placed(self.storeys[s.storey].ObjectPlacement, (0.0, 0.0, 0.0))
        e.Representation = self.body(
            self.prism(s.outline, s.z1 - total - self.h.storeys[s.storey], total)
        )
        ordered = s.layers if s.sense == "NEGATIVE" else tuple(reversed(s.layers))
        ls = self.layer_set(s.type_name or s.name, ordered)
        self.usage(e, ls, "AXIS3", s.sense, 0.0)
        if s.type_name:
            ifcopenshell.api.type.assign_type(
                self.f,
                related_objects=[e],
                relating_type=self.type_of("IfcSlabType", s.type_name),
                should_map_representations=False,
            )
        self.contained[s.storey].append(e)

    def space(self, sp: SpaceSpec) -> None:
        e = self.entity("IfcSpace", f"space/{sp.name}", sp.name)
        e.LongName = sp.long_name
        e.ObjectPlacement = self.placed(self.storeys[sp.storey].ObjectPlacement, (0.0, 0.0, 0.0))
        e.Representation = self.body(
            self.prism(sp.outline, sp.z0 - self.h.storeys[sp.storey], sp.height)
        )
        if sp.parent:
            ifcopenshell.api.aggregate.assign_object(
                self.f, products=[e], relating_object=self.storeys[sp.storey]
            )


def write(h: House, path: Path) -> dict[str, str]:
    """Write the file; the result maps the name of each element to its GlobalId."""
    return Writer(h).write(path)
